[project]
name = "streamlit-mc-simulator"
version = "0.1.0"
description = "Streamlit MC simulator (very simple)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "pytest>=8.3.4",
    "streamlit>=1.40.2",
]
